#!/usr/bin/env bash
# Configure the existing Cloudflare Tunnel using canonical environment values generated by Utils.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
ACTION="${1:-init}"

: "${ANU_HOME:?ANU_HOME is required}"
: "${ANU_DEPLOY_PUBLIC_UI_HOST:?ANU_DEPLOY_PUBLIC_UI_HOST is required}"
: "${ANU_DEPLOY_PUBLIC_API_HOST:?ANU_DEPLOY_PUBLIC_API_HOST is required}"
: "${ANU_DEPLOY_PUBLIC_EXPLORER_HOST:?ANU_DEPLOY_PUBLIC_EXPLORER_HOST is required}"
: "${ANU_DEPLOY_CLOUDFLARE_TUNNEL_NAME:?ANU_DEPLOY_CLOUDFLARE_TUNNEL_NAME is required}"
: "${ANU_DEPLOY_CLOUDFLARE_FRONTEND_ORIGIN_URL:?ANU_DEPLOY_CLOUDFLARE_FRONTEND_ORIGIN_URL is required}"
: "${ANU_DEPLOY_CLOUDFLARE_BACKEND_ORIGIN_URL:?ANU_DEPLOY_CLOUDFLARE_BACKEND_ORIGIN_URL is required}"
: "${ANU_DEPLOY_CLOUDFLARE_EXPLORER_ORIGIN_URL:?ANU_DEPLOY_CLOUDFLARE_EXPLORER_ORIGIN_URL is required}"
: "${ANU_DEPLOY_CLOUDFLARE_ORIGIN_SERVER_NAME:?ANU_DEPLOY_CLOUDFLARE_ORIGIN_SERVER_NAME is required}"

CLOUDFLARED_BIN="$(command -v cloudflared || true)"
[[ -n "$CLOUDFLARED_BIN" ]] || { echo "ERROR: cloudflared is not installed" >&2; exit 1; }

if [[ "$ACTION" =~ ^(init|start|stop|restart|status|destroy)$ ]] && [[ "$(id -u)" -ne 0 ]]; then
  exec sudo -E "$0" "$ACTION"
fi

resolve_tunnel_id() {
  local lookup_user="$1"
  if [[ -n "${ANU_DEPLOY_CLOUDFLARE_TUNNEL_ID}" ]]; then
    printf '%s\n' "$ANU_DEPLOY_CLOUDFLARE_TUNNEL_ID"
    return
  fi
  sudo -u "$lookup_user" "$CLOUDFLARED_BIN" tunnel list 2>/dev/null |
    awk -v tunnel_name="$ANU_DEPLOY_CLOUDFLARE_TUNNEL_NAME" \
      'NR > 1 && $2 == tunnel_name {print $1; exit}'
}

install_tunnel() {
  local service_user service_group tunnel_id credentials_source credentials_target
  service_user="$ANU_DEPLOY_CLOUDFLARE_SERVICE_USER"
  [[ -n "$service_user" ]] || service_user="${SUDO_USER:-$(id -un)}"
  service_group="$ANU_DEPLOY_CLOUDFLARE_SERVICE_GROUP"
  [[ -n "$service_group" ]] || service_group="$(id -gn "$service_user")"

  tunnel_id="$(resolve_tunnel_id "$service_user")"
  [[ -n "$tunnel_id" ]] || {
    echo "ERROR: unable to resolve Cloudflare tunnel ID" >&2
    exit 1
  }

  credentials_target="$ANU_HOME/cloudflare/credentials.json"
  credentials_source="$ANU_DEPLOY_CLOUDFLARE_CREDENTIALS_SOURCE"
  if [[ -z "$credentials_source" ]]; then
    local service_home
    service_home="$(getent passwd "$service_user" | cut -d: -f6)"
    credentials_source="$service_home/.cloudflared/$tunnel_id.json"
  fi

  install -d -m 0750 -o "$service_user" -g "$service_group" "$ANU_HOME/cloudflare"
  if [[ ! -s "$credentials_target" ]]; then
    [[ -s "$credentials_source" ]] || {
      echo "ERROR: tunnel credentials not found: $credentials_source" >&2
      exit 1
    }
    install -m 0600 -o "$service_user" -g "$service_group" \
      "$credentials_source" "$credentials_target"
  fi

  sed \
    -e "s|@CLOUDFLARE_TUNNEL_ID@|$tunnel_id|g" \
    -e "s|@CLOUDFLARE_CREDENTIALS_FILE@|$credentials_target|g" \
    -e "s|@PUBLIC_UI_HOST@|$ANU_DEPLOY_PUBLIC_UI_HOST|g" \
    -e "s|@PUBLIC_API_HOST@|$ANU_DEPLOY_PUBLIC_API_HOST|g" \
    -e "s|@PUBLIC_EXPLORER_HOST@|$ANU_DEPLOY_PUBLIC_EXPLORER_HOST|g" \
    -e "s|@FRONTEND_ORIGIN_URL@|$ANU_DEPLOY_CLOUDFLARE_FRONTEND_ORIGIN_URL|g" \
    -e "s|@BACKEND_ORIGIN_URL@|$ANU_DEPLOY_CLOUDFLARE_BACKEND_ORIGIN_URL|g" \
    -e "s|@EXPLORER_ORIGIN_URL@|$ANU_DEPLOY_CLOUDFLARE_EXPLORER_ORIGIN_URL|g" \
    -e "s|@ORIGIN_SERVER_NAME@|$ANU_DEPLOY_CLOUDFLARE_ORIGIN_SERVER_NAME|g" \
    -e "s|@NEBULA_HOME@|$ANU_HOME|g" \
    "$ROOT/cloud/cloudflare/templates/config.yml.template" > "$ANU_HOME/cloudflare/config.yml"
  chown "$service_user:$service_group" "$ANU_HOME/cloudflare/config.yml"
  chmod 0640 "$ANU_HOME/cloudflare/config.yml"

  sed \
    -e "s|@CLOUDFLARED_BIN@|$CLOUDFLARED_BIN|g" \
    -e "s|@NEBULA_HOME@|$ANU_HOME|g" \
    -e "s|@SERVICE_USER@|$service_user|g" \
    -e "s|@SERVICE_GROUP@|$service_group|g" \
    "$ROOT/cloud/cloudflare/templates/cloudflared.service.template" \
    > /etc/systemd/system/cloudflared.service

  systemctl daemon-reload
  systemctl enable cloudflared.service
  systemctl enable docker.service
  echo "Cloudflare tunnel configured: $tunnel_id"
}


destroy_tunnel_configuration() {
  # Destructive cleanup removes deployment-owned host integration and credentials but leaves
  # Cloudflare account-side tunnel deletion to the operator/cloud provider account boundary.
  systemctl stop cloudflared.service >/dev/null 2>&1 || true
  systemctl disable cloudflared.service >/dev/null 2>&1 || true
  rm -f /etc/systemd/system/cloudflared.service
  systemctl daemon-reload
  rm -rf "$ANU_HOME/cloudflare"
  echo "Cloudflare host configuration removed."
}

case "$ACTION" in
  init) install_tunnel ;;
  start|stop|restart|status) systemctl "$ACTION" cloudflared.service ;;
  destroy) destroy_tunnel_configuration ;;
  *) echo "ERROR: unsupported action: $ACTION" >&2; exit 2 ;;
esac
