"""Cloudflare Tunnel host integration for LOCAL and OCI deployments.

The Cloudflare adapter is deliberately independent from the application lifecycle. It reuses the
same canonical profile environment generated by ``deploy.environment`` and delegates tunnel/service
installation to the proven Cloudflare setup script copied from ``agent-nebula-deploy``.
"""

from __future__ import annotations

import argparse
import os
import subprocess
from dataclasses import dataclass
from pathlib import Path
from typing import Mapping, Protocol

from deploy.environment import DeploymentEnvironmentService

from .targets import DeploymentTarget


class CloudflareCommandRunner(Protocol):
    """Execute the existing Cloudflare host adapter with an explicit environment."""

    def run(self, argv: tuple[str, ...], *, environment: Mapping[str, str]) -> None:
        """Execute one Cloudflare adapter command and raise when it fails."""


class SubprocessCloudflareCommandRunner:
    """Production command runner backed by ``subprocess.run``."""

    def run(self, argv: tuple[str, ...], *, environment: Mapping[str, str]) -> None:
        """Execute one argument vector without invoking a shell."""

        subprocess.run(argv, env=dict(environment), check=True)


@dataclass(frozen=True, slots=True)
class CloudflareTunnelService:
    """Configure and operate the deployment-owned Cloudflare Tunnel host integration."""

    repository_root: Path
    target: DeploymentTarget
    runner: CloudflareCommandRunner | None = None

    _ACTIONS = frozenset({"init", "start", "stop", "restart", "status", "destroy"})

    def execute(self, action: str, *, profile: str = "cloudflare") -> None:
        """Run one independent Cloudflare lifecycle action using canonical deployment settings."""

        if action not in self._ACTIONS:
            raise ValueError(f"Unsupported Cloudflare action: {action}")
        if profile != "cloudflare":
            raise ValueError("Cloudflare Tunnel requires PROFILE=cloudflare")

        environment_service = DeploymentEnvironmentService(target=self.target)
        if action == "init":
            deployment_environment = environment_service.generate(product="nebula", profile=profile)
        else:
            deployment_environment = environment_service.load(product="nebula", profile=profile)

        script = self.repository_root / "cloud" / "cloudflare" / "setup.sh"
        if not script.is_file():
            raise FileNotFoundError(f"Cloudflare setup script not found: {script}")

        process_environment = os.environ.copy()
        process_environment.update(deployment_environment.values)
        command_runner = self.runner or SubprocessCloudflareCommandRunner()
        command_runner.run((str(script), action), environment=process_environment)


def _build_parser() -> argparse.ArgumentParser:
    """Build the command-line parser for independent Cloudflare host operations."""

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("action", choices=tuple(sorted(CloudflareTunnelService._ACTIONS)))
    parser.add_argument(
        "--target",
        choices=tuple(target.value for target in DeploymentTarget),
        default=DeploymentTarget.LOCAL.value,
    )
    parser.add_argument("--profile", choices=("cloudflare",), default="cloudflare")
    return parser


def main() -> int:
    """Execute the selected Cloudflare host operation."""

    args = _build_parser().parse_args()
    CloudflareTunnelService(
        repository_root=Path(__file__).resolve().parents[1],
        target=DeploymentTarget(args.target),
    ).execute(args.action, profile=args.profile)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
