"""Resolve target-specific image references and generate Compose image overrides.

The base Compose files preserve the proven Agent Nebula service topology. A generated override file
changes only image references, allowing the same Compose definitions to run local AMD64 images or
OCI ARM64 images from GHCR without introducing target-specific branches in application services.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from .images import ImageConfigurationRepository, registry_image_reference
from .targets import DeploymentTarget


_SERVICE_IMAGES: dict[str, dict[str, str | None]] = {
    "nebula": {
        "nebula-database": None,
        "migrate": "core",
        "nebula-core": "core",
        "nebula-console": "console",
        "nebula-explorer": "explorer",
    },
    "oauth": {"nebula-oauth": "oauth"},
    "policy": {"nebula-policy": "policy"},
    "playground": {
        "playground-container": "playground-container",
        "playground-backend": "playground-backend",
        "playground-ui": "playground-ui",
    },
}


@dataclass(frozen=True, slots=True)
class DeploymentImageResolver:
    """Resolve one release into local or OCI image references from shared image configuration."""

    repository_root: Path
    target: DeploymentTarget
    release: str

    def references(self) -> dict[str, str]:
        """Return enabled logical image names mapped to target-specific Docker references."""

        configuration = ImageConfigurationRepository(
            self.repository_root / "config" / "images.json",
            self.repository_root / "config" / "registry.json",
        )
        _, specs = configuration.load_manifest()
        registry = configuration.load_registry()
        tag = f"{self.release}-{self.target.architecture}"
        references: dict[str, str] = {}
        for spec in specs:
            if not spec.enabled:
                continue
            if self.target is DeploymentTarget.LOCAL:
                references[spec.name] = f"agent-nebula/{spec.image}:{tag}"
            else:
                references[spec.name] = registry_image_reference(
                    registry.host,
                    registry.namespace,
                    registry.project,
                    spec.image,
                    tag,
                )
        return references


@dataclass(frozen=True, slots=True)
class ComposeImageOverrideService:
    """Generate minimal Compose overrides containing only target-specific image references."""

    repository_root: Path
    target: DeploymentTarget
    release: str

    def write(self, *, product: str, destination: Path) -> Path:
        """Write one deterministic Compose override for the selected product and return its path."""

        services = _SERVICE_IMAGES.get(product)
        if services is None:
            raise ValueError(f"Unsupported Compose product: {product}")
        references = DeploymentImageResolver(
            self.repository_root,
            self.target,
            self.release,
        ).references()

        lines = ["# Generated by Agent Nebula Deploy OCI. Do not edit.", "services:"]
        for service, logical_image in services.items():
            image = "postgres:17" if logical_image is None else references.get(logical_image)
            if image is None:
                raise ValueError(
                    f"No enabled image configuration for {logical_image!r} required by {service!r}"
                )
            lines.extend((f"  {service}:", f"    image: {image}"))

        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_text("\n".join(lines) + "\n", encoding="utf-8")
        return destination
